language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
deploy:
  provider: heroku
  api_key:
    secure: ZY20IIlKVOyDyBPFjvjbo4HE+RVddqbeYqrpp5em2QjtSz4g0U8cf7E1niIDKDBt5C4h7n9eUMH6EDTLCn/+DPj1GfFu8FtDIBK5XEuODYWNu7yORUO8jVlTdnSShr5jOHt++XrhjTHJvTOvm705Qqyqph7PcV6rFtS5z+f38RZLjy5r6ij8W6AUzErCKexYh/rithmFRFMzf8SJ/5PD13FQJnQ+Wi90Sc1ZdXgHisxTL8gzZg0vKm4QJMnzxXGrKZFIunhGicdPZ6WcMQj+xZGPb1rZEnTfspMnTOrA8o8baesWcEkzyCZdSwcy5S1mKtlGoOFnFdhVj5t28XhiNECWXA1yYewWUW6owL2ELFIOk/XKzkNXpHOZJLoHBbR0yT+EIbPmye7HuuANtEz6y0KZ/H7Be259EbXxJ+8qb8HAEefrWGHw7sYqEtFIYQFpSbDUmCnVvI4U6sl3hfs9mrqEcA5CLYS5kronvc0oTQVj4vKTnSw2Fj3itrAt+3yJ1uGLSgOk7NJIzjfb1IpA0EUCstvgcylao/E0Ar9vxl5kitBElFYReC8tRZFmdv9bTP8aOPITaIlLMiqGcLvYIY0aCBeBlsMBBPBaRotgAy3zUkvrx/BBgwapo21/I2GR47RhQRDU/SAZOVP5EUBrxLqIhoYWFTnFFN7q9yVFUtM=
  app: lr-register-metadata-alpha
  on:
    repo: LandRegistry/register-metadata
    branch: master
notifications:
  slack:
    secure: PAfVN2y78998sGoCgNKFhYroCImkRMqY78jUw3azB580si+tbqJeIMXT9dDafj9/Ydx+ZHZBZJT+5f4my9z5Tz//84za/Y1m7y9yta36dqXEfM8t8vHbT8fgc4qnon+lEUi5mRFc9YpwBKrpPduOl6GwNk7O5IJmX/QpLwTDxdo3+GBdwK2/eT6EFhsacbov0N+ZRnhHz92Nn6EGnHHBoyQ5Rdgld0lL3QChoIEWzpFuVASnDJ/75/vOC3I0Qo7JShMvQl0/H/s1H5D25T3vHgm+HqE9V/Tv1/MiiWyJQyOhVjAHaBLCzicQsFWQH+UXJxAsEn8mfN1BW1Q/cpUvJVKnCfCtUhX5wVETPk4Pj6T8LTkLhGGSimHnOKlnhoZnGPev5/qAHftRlQO3TuHnpirR64D23YB6VVZNgPbiX/cztzt2s58eChOJ2nXYet9y4+paB+yX2KWQ63DvJXmbHyP34EDIkio9NJa1lOFgoykppm8t/BAfPNA98TaFtxajYeDLHlGu5i0sJ0FwLXmEqUgVbCLcHpYwcBnqUbKPdynOfSfMaIapy3irqU2LhCk/miQlxNazthGhk2or9WgR02gfstvkMVEwWPljbo36uG3/Ga+cdEayKZRVsnNAFreoG632esBpILxRMmjiJ7sL0BcNLEYWerkQ1slH8oe47M0=
