"""empty message

Revision ID: 10987d241fde
Revises: None
Create Date: 2015-06-26 14:38:10.484352

"""

# revision identifiers, used by Alembic.
revision = '10987d241fde'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cre',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('template', sa.String(), nullable=True),
    sa.Column('infills', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cre')
    ### end Alembic commands ###
