"""empty message

Revision ID: 3680c3777428
Revises: 6a7d6bc8f5d
Create Date: 2015-07-03 09:50:42.534201

"""

# revision identifiers, used by Alembic.
revision = '3680c3777428'
down_revision = '6a7d6bc8f5d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cre', sa.Column('restriction_name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cre', 'restriction_name')
    ### end Alembic commands ###
