"""empty message

Revision ID: 3857d7751f2a
Revises: 3f837c9f110d
Create Date: 2015-08-12 12:00:50.467833

"""

# revision identifiers, used by Alembic.
revision = '3857d7751f2a'
down_revision = '3f837c9f110d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cre', sa.Column('sub_role_code', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cre', 'sub_role_code')
    ### end Alembic commands ###
