"""empty message

Revision ID: 425ea7686adb
Revises: 276a647f828a
Create Date: 2015-06-29 11:41:15.212572

"""

# revision identifiers, used by Alembic.
revision = '425ea7686adb'
down_revision = '276a647f828a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mdref',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('mdref', sa.String(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('code', 'version')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mdref')
    ### end Alembic commands ###
