"""empty message

Revision ID: 6a7d6bc8f5d
Revises: 276a647f828a
Create Date: 2015-06-29 13:52:11.644043

"""

# revision identifiers, used by Alembic.
revision = '6a7d6bc8f5d'
down_revision = '276a647f828a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mdref',
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('mdref', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('mdref', 'sequence', 'entry_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mdref')
    ### end Alembic commands ###
